### ISSUE TITLE
picom: crash when unmap

### ISSUE THREAD

**Issue by wael444** [FT-Labs/pdwm#21]
using [dccsillag/picom](https://github.com/dccsillag/picom/tree/implement-window-animations), nothing happens, but when using [FT-Labs/picom](https://github.com/FT-Labs/picom), picom crashes when windows are unmapped/closed.

i am opening here since [FT-Labs/picom](https://github.com/FT-Labs/picom) has issues disabled

to recreate:
1. have a window
2. have FT-Labs/picom running
2. close it

**Comment by wael444** [comment]
i would also like to point out i am not using pdwm, and for all i know ft-lab picom fork only works well with pdwm. i have applied https://github.com/FT-Labs/pdwm/commit/a26eed600933f673f28753baef5ccf00a261e1f9, https://github.com/FT-Labs/pdwm/commit/8fe5f085403dfabdefbde3c38b6c17cdf8eb0557, https://github.com/FT-Labs/pdwm/commit/33e9e31c739dbf449ad4b577b86dc18d504a9a27 to my fork of dwm, what am i missing?

**Comment by FT-Labs** [comment]
Hello,

Ive opened issues on picom repo. Could you redirect this to here, with passing a link to your dwm? Thanks

**Comment by wael444** [comment]
........ GITHUB CAN ALLOW YOU TO TRANSFER ISSUES TO ANOTHER REPOSITORY

**Comment by FT-Labs** [comment]
Can you link it
